name: Buid and deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build_maven:
    runs-on: ubuntu-20.04
    steps:
      - name: Clean workspace after
        uses: mickem/clean-after-action@v1

      - name: Setup workspace
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Install dependencies
        run: mvn --batch-mode clean validate

      - name: Packaging
        run: mvn --batch-mode package

      - name: Move to actifacts folder
        run: |
          mkdir ~/artifacts
          mv target/ApiServer-1.0-jar-with-dependencies.jar ~/artifacts/KomgaAPI.jar
          ls -lah ~/artifacts

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: Temporary artifacts
          path: ~/artifacts
          if-no-files-found: error
          retention-days: 1
