name: CI

on:
  push:
    branches: [ master, remade_unit_test ]
  pull_request:
    branches: [ master, remade_unit_test ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Install dependencies
        run: mvn validate
      - name: Pass test
        run: mvn test
